'use client'

import './globals.css'
import Header from '@/components/Header'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
import { ReactQueryProvider } from './react-query-provider'
import { SolanaProvider } from '@/components/solana-provider'

const metadata = {
  title: 'CrowdSolFund',
  description: 'Generated by create-solana-dapp',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#030303] text-white">
        <ReactQueryProvider>
          <SolanaProvider>
            <Header />
            <main className="min-h-screen">
              {children}
            </main>
          </SolanaProvider>

          <ToastContainer
            position="bottom-center"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="dark"
          />
        </ReactQueryProvider>
      </body>
    </html>
  )
}
